"""initial

Revision ID: 79b2f9dcb807
Revises: 701ab87b605c
Create Date: 2026-04-18 00:23:32.851012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b2f9dcb807'
down_revision: Union[str, Sequence[str], None] = '701ab87b605c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('revolving_utilization', sa.Float(), nullable=True),
    sa.Column('num_open_credit_lines', sa.Integer(), nullable=True),
    sa.Column('num_real_estate_loans', sa.Integer(), nullable=True),
    sa.Column('num_late_30_59', sa.Integer(), nullable=True),
    sa.Column('num_late_60_89', sa.Integer(), nullable=True),
    sa.Column('num_late_90', sa.Integer(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_label', sa.String(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_predictions_id'), 'credit_predictions', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_credit_predictions_id'), table_name='credit_predictions')
    op.drop_table('credit_predictions')
    # ### end Alembic commands ###
